[build]
 functions='./functions'

  [functions.timeout]
    timeout = 60  # Set the timeout to 60 seconds (or your preferred duration)

[[redirects]]
  force = true
  from ="/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
