name: simple echo

on: [push]
env:
  WF_VAL: Available for all
jobs:
  run-github-actions:
    permissions:
      contents: wite
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm i
      - name: run test
        run: npm test
      - name: print env var
        run: echo ${WF_VAL}
